FROM golang:1.12
WORKDIR /go/src/rest-service-mimic/
COPY . /go/src/rest-service-mimic
ENV GO111MODULE="on"
ENV CGO_ENABLED=0
ENV GOOS=linux
ENTRYPOINT ["go", "build", "-o", "/output/rest-service-mimic"]
